version: "3.8"

services:
  db:
    image: postgres:15
    container_name: traval_postgres
    environment:
      POSTGRES_DB: traval_db
      POSTGRES_USER: traval_db_user
      POSTGRES_PASSWORD: Me9ky3wAd2mYf4CWWvLQs5PBzXgMUqxT
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/traval_init_postgres.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
