services:
  - type: web
    name: travel-feedback-collector
    env: docker
    plan: free
    dockerfilePath: backend/Dockerfile   # Adjusted path to your backend Dockerfile
    buildCommand: "./mvnw clean package -DskipTests"  # Build command for your backend
    startCommand: "java -jar target/*.jar"  # Start command for your Java app (adjust if necessary)
    envVars:
      - key: JDBC_DATABASE_URL
        value: jdbc:postgresql://dpg-d45drjmuk2gs73cfg84g-a.oregon-postgres.render.com:5432/traval_db
      - key: DB_USERNAME
        value: traval_db_user
      - key: DB_PASSWORD
        value: Me9ky3wAd2mYf4CWWvLQs5PBzXgMUqxT
      - key: SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_TIME_ZONE
        value: Asia/Kolkata
