services:
  - type: web
    name: travel-feedback-backend
    env: docker
    plan: free
    dockerfilePath: backend/Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d45drjmuk2gs73cfg84g-a.oregon-postgres.render.com:5432/traval_db
      - key: SPRING_DATASOURCE_USERNAME
        value: traval_db_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: Me9ky3wAd2mYf4CWWvLQs5PBzXgMUqxT
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_SHOW_SQL
        value: true
      - key: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_TIME_ZONE
        value: Asia/Kolkata
